export const EXAMPLE_BINGO: string[] = [
    'Craft a Diamond Pickaxe',
    'Mine 10 Diamond Ore',
    'Defeat a Creeper with a Sword',
    'Tame a Wolf or Cat',
    'Enter the Nether',
    'Build a Nether Portal',
    'Find a Village',
    'Trade with a Villager That Is a Very Long Sentence and This Sentence Just Keeps Getting Longer With Lots of Stuff In It',
    'Brew a Potion',
    'Craft a Book and Quill',
    'Enchant an Item',
    'Build a Redstone Contraption',
    'Locate a Stronghold',
    'Defeat an Enderman',
    'Beat a Skeleton without Armor',
    'Smelt 64 Iron Ingots',
    'Find a Jungle Temple',
    'Capture a Rabbit',
    'Catch a Fish',
    'Collect 10 Different Flowers',
    'Build a Medieval Castle',
    'Discover a Mushroom Island',
    'Win a PvP Fight',
    'Locate an Ocean Monument',
    'Defeat the Ender Dragon',
]
